// GPIO
#define GPIO_BRAIN_MIDI 9
#define GPIO_BRAIN_LED 10

#define GPIO_PULSE_INPUT 3
#define GPIO_PULSE_OUTPUT 8

#define GPIO_BRAIN_POTMUX_ADC 26
#define GPIO_BRAIN_POTMUX_S0 16
#define GPIO_BRAIN_POTMUX_S1 17

// MIDI
#define MIDI_CHANNEL 1